/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projekte;

import projekte.Builder.MainBase;

public class App {
    public static void main(String[] args) {
        MainBase base = new MainBase();
        base.start();
    }
}
